package edu.iastate.cs472.proj1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
/**
 *
 * @Pulkit Saxena
 *
 */
public class EightPuzzle {
	/**
	 * This static method solves an 8-puzzle with a given initial state using three heuristics. The
	 * first two, allowing single moves only, compare the board configuration with the goal configuration
	 * by the number of mismatched tiles, and by the Manhattan distance, respectively.  The third
	 * heuristic, designed by yourself, allows double moves and must be also admissible.  The goal
	 * configuration set for all puzzles is
	 *
	 * 			1 2 3
	 * 			8   4
	 * 			7 6 5
	 *
	 * @param s0
	 * @return a string specified in the javadoc below
	 */
	public static String solve8Puzzle(State s0) {


		// TODO\
		/*
		  1) If there exists no solution, return a message that starts with "No solution
		    exists for the following initial state:" and follows with a blank line and
		    then what would be the output from a call s0.toString(). See the end of
		    Section 6 in the project description for an example.


		 2) Otherwise, solve the puzzle with the three heuristics.  The two solutions generated by
		    the first two heuristics may be different but must have the same length for optimality.
		 */

		if (!s0.solvable()) {
			return "No solution exists for the following initial state:\n\n" + s0.toString();
		}

		Heuristic[] heuristics = new Heuristic[] {
				Heuristic.TileMismatch,
				Heuristic.ManhattanDist,
				Heuristic.DoubleMoveHeuristic
		};

		StringBuilder out = new StringBuilder();
		for (int i = 0; i < heuristics.length; i++) {
			// Run A* for this heuristic and append its block.
			String block = AStar(s0, heuristics[i]);
			out.append(block);
			if (i < heuristics.length - 1) out.append("\n"); // blank line between blocks
		}
		return out.toString();
	}

	/**
	 * This method implements the A* algorithm to solve the 8-puzzle with an input initial state s0.
	 * The algorithm implementation is described in Section 3 of the project description.
	 *
	 * Precondition: the puzzle is solvable with the initial state s0.
	 *
	 * @param s0  initial state
	 * @param h   heuristic
	 * @return    solution string
	 */
	public static String AStar(State s0, Heuristic h) {

		State.heu = h;


		s0.numMoves = 0;
		s0.predecessor = null;
		s0.previous = null;
		s0.move = null;

		OrderedStateList OPEN = new OrderedStateList(h, true);
		OrderedStateList CLOSE = new OrderedStateList(h, false);

		OPEN.addState(s0);

		while (OPEN.size() > 0) {
			State s = OPEN.remove();

			if (s.isGoalState()) {

				return solutionPath(s, h);
			}

			CLOSE.addState(s);

			Move[] possibleMoves;
			if (h == Heuristic.DoubleMoveHeuristic) {
				possibleMoves = Move.values();
			} else {
				possibleMoves = new Move[] { Move.LEFT, Move.RIGHT, Move.UP, Move.DOWN }; // single moves only
			}

			for (Move m : possibleMoves) {
				try {
					State t = s.successorState(m);
					if (t == null) continue;


					if (s.predecessor != null && t.equals(s.predecessor)) continue;

					State inOpen = OPEN.findState(t);
					State inClose = CLOSE.findState(t);

					if (inOpen == null && inClose == null) {
						OPEN.addState(t);
					} else if (inOpen != null) {

						if (t.cost() < inOpen.cost()) {
							OPEN.removeState(inOpen);
							OPEN.addState(t);
						}
					} else {
						if (t.cost() < inClose.cost()) {
							CLOSE.removeState(inClose);
							OPEN.addState(t);
						}
					}
				} catch (IllegalArgumentException ignored) {
					// Invalid move from this state; skip
				}
			}
		}

		return "No solution found\n";
	}

	/**
	 * From a goal state, follow the predecessor link to trace all the way back to the initial state.
	 * Meanwhile, generate a string to represent board configurations in the reverse order, with
	 * the initial configuration appearing first. Between every two consecutive configurations
	 * is the move that causes their transition. A blank line separates a move and a configuration.
	 * In the string, the sequence is preceded by the total number of moves and a blank line.
	 *
	 * See Section 6 in the projection description for an example.
	 *
	 * Call the toString() method of the State class.
	 *
	 * @param goal
	 * @return
	 */
	private static String solutionPath(State goal, Heuristic h) {
		List<State> path = new ArrayList<>();
		for (State cur = goal; cur != null; cur = cur.predecessor) {
			path.add(cur);
		}
		Collections.reverse(path);

		StringBuilder sb = new StringBuilder();
		sb.append(path.size() - 1)
				.append(" moves in total (heuristic: ")
				.append(humanHeuristicLabel(h))
				.append(")\n\n"); // header + blank line

		for (int i = 0; i < path.size(); i++) {
			sb.append(path.get(i).toString()).append("\n");
			// Print the move BETWEEN states, i.e., the move that led to the NEXT state
			if (i < path.size() - 1 && path.get(i + 1).move != null) {
				sb.append(path.get(i + 1).move.toString()).append("\n");
			}
		}
		return sb.toString();
	}

	private static String humanHeuristicLabel(Heuristic h) {
		switch (h) {
			case TileMismatch:
				return "number of mismatched tiles";
			case ManhattanDist:
				return "the Manhattan distance";
			case DoubleMoveHeuristic:
				return "double moves allowed";
			default:
				return h.toString();
		}
	}
}
