package edu.iastate.cs472.proj1;

import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *  
 * @author: Pulkit Saxena
 *
 */

public class PuzzleSolver 
{
	/**
	 *  Read an initial state from the input file.  Solve the eight puzzle three times:
	 *  
	 *      1) The first solution allows single moves only and uses the heuristic based on the number
	 *         of mismatched tiles. 
	 *         
	 *      2) The second solution also allows single moves only but uses the heuristic based on the 
	 *         Manhattan distance. 
	 *         
	 *      3) The third solution allows single and double moves and uses the admissible heuristic 
	 *         designed by yourself.  
	 *         
	 *  Each solution is printed out as a sequence of states, generated by single/double moves, from the 
	 *  initial state to the goal state. If no solution exists, report it.  
	 * 
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist 
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */



		public static void main(String[] args) {
			Scanner sc = new Scanner(System.in);

			System.out.println("=== 8 Puzzle Solver ===");
			System.out.print("Enter the puzzle input file name (e.g., 8Puzzle.txt): ");
			//String fileName = sc.nextLine().trim();
			String fileName = "8Puzzle.txt";
			System.out.println("DEBUG: Using filename " + fileName);


			try {

				State initial = new State(fileName);

				if (!initial.solvable()) {
					System.out.println("No solution exists for the following initial state:\n");
					System.out.println(initial);
					System.out.println("Solvable? " + initial.solvable() );
					return;
				}

				String solution = EightPuzzle.solve8Puzzle(initial);


				System.out.println(solution);

			} catch (IllegalArgumentException e) {
				System.out.println("Invalid input format in file: " + fileName);
				e.printStackTrace();
			} catch (FileNotFoundException e) {
				System.out.println("File not found: " + fileName);
			}

			sc.close();
		}
	}




