package edu.iastate.cs472.proj1;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

//import static com.sun.tools.javac.jvm.ByteCodes.swap;
import static java.util.Collections.swap;

/**
 *  
 * @author Pulkit Saxena
 *
 */


/**
 * This class represents a board configuration in the 8-puzzle.  Only the initial configuration is 
 * generated by a constructor, while intermediate configurations will be generated via calling
 * the method successorState().  State objects will form two circular doubly-linked lists OPEN and 
 * CLOSED, which will be used by the A* algorithm to search for a path from a given initial board
 * configuration to the final board configuration below: 
 * 
 *  1 2 3 
 *  8   4
 *  7 6 5
 *
 * The final configuration (i.e., the goal state) above is not explicitly represented as an object 
 * of the State class. 
 */

public class State implements Cloneable, Comparable<State>
{
	public int[][] board; 		// configuration of tiles 
	
	public State previous;    	// previous node on the OPEN/CLOSED list
	public State next; 			// next node on the OPEN/CLOSED list
	public State predecessor; 	// predecessor node on the path from the initial state

	public Move move;           // the move that generated this state from its predecessor
	public int numMoves; 	    // number of moves from the initial state to this state

	public static Heuristic heu; // heuristic used. shared by all the states. 
	
	private int numMismatchedTiles = -1;    // number of mismatched tiles between this state 
	                                        // and the goal state; negative if not computed yet.
	private int ManhattanDistance = -1;     // Manhattan distance between this state and the 
	                                        // goal state; negative if not computed yet. 
	private int numSingleDoubleMoves = -1;  // number of single and double moves with each double 
										    // move counted as one; negative if not computed yet.
											private static final int[][] GOAL = {
													{1, 2, 3},
													{8, 0, 4},
													{7, 6, 5}
											};


	/**
	 * Constructor (for the initial state).  
	 * 
	 * It takes a 2-dimensional array representing an initial board configuration. The empty 
	 * square is represented by the number 0.  
	 * 
	 *     a) Initialize all three links previous, next, and predecessor to null.  
	 *     b) Set move to null and numMoves to zero.
	 * 
	 * @param board
	 * @throws IllegalArgumentException		if board is not a 3X3 array or its nine entries are 
	 * 										not respectively the digits 0, 1, ..., 8. 
	 */
    public State(int[][] board) throws IllegalArgumentException 
    {
    	// TODO
		if(board.length == 0){
			throw new IllegalArgumentException();
		}
		for (int c = 0; c < board.length; c++){
			if (board[c].length != 3){
				throw new IllegalArgumentException();
			}
		}
		for (int row = 0; row < board.length; row++){
			for (int col = 0; col < board[row].length; col++){
				int value = board[row][col];
				if(value < 0 || value >8){
					throw new IllegalArgumentException();
				}
			}
		}
		this.board = board;
		numMoves = 0;
		move = null;
		previous = null;
        predecessor = null;

	}
    
    
    /**
     * Constructor (for the initial state) 
     * 
     * It takes a state from an input file that has three rows, each containing three digits 
     * separated by exactly one blank.  Every row starts with a digit. The nine digits are 
     * from 0 to 8 with no duplicates.  
     * 
     * Do the same initializations as for the first constructor. 
     * 
     * @param inputFileName
     * @throws FileNotFoundException
     * @throws IllegalArgumentException  if the file content does not meet the above requirements. 
     */
	public State(String inputFileName) throws FileNotFoundException, IllegalArgumentException {
		Scanner scanner = new Scanner(new File(inputFileName));
		int[][] tempBoard = new int[3][3];
		int row = 0;

		while (scanner.hasNextLine()) {
			String line = scanner.nextLine().trim();
			if (line.isEmpty()) {

				continue;
			}


			String[] parts = line.split("\\s+");
			if (parts.length != 3) {
				throw new IllegalArgumentException();
			}

			for (int col = 0; col < 3; col++) {
				int value = Integer.parseInt(parts[col]);
				if (value < 0 || value > 8) {
					throw new IllegalArgumentException();
				}
				tempBoard[row][col] = value;
			}

			row++;
		}

		scanner.close();

		// After reading, check that we got exactly 3 rows
		if (row != 3) {
			throw new IllegalArgumentException();
		}

		this.board = tempBoard;
		numMoves = 0;
		move = null;
		previous = null;
		predecessor = null;
	}


	/**
     * Generate the successor state resulting from a given move.  Throw an exception if the move
     * cannot be executed.  Besides setting the array board[][] properly, you also need to do the
     * following:
     *
     *     a) set the predecessor of the successor state to this state;
     *     b) set the private instance variable move of the successor state to the parameter m;
     *     c) Set the links next and previous to null;
     *     d) Set the variable numMoves for the successor state to this.numMoves + 1.
     *
     * @param m  one of the moves LEFT, RIGHT, UP, DOWN, DBL_LEFT, DBL_RIGHT, DBL_UP, and DBL_DOWN
     * @return null  			if the successor state is this.predecessor
     *         successor state  otherwise
     * @throws IllegalArgumentException if LEFT when the empty square is in the right column, or
     *                                  if RIGHT when the empty square is in the left column, or
     *                                  if UP when the empty square is in the bottom row, or
     *                                  if DOWN when the empty square is in the top row, or
     *                                  if DBL_LEFT when the empty square is not in the left column, or
     *                                  if DBL_RIGHT when the empty square is not in the right column, or
     *                                  if DBL_UP when the empty square is not in the top row, or
     *                                  if DBL_DOWN when the empty square is not in the bottom row.
     */
    public State successorState(Move m) throws IllegalArgumentException
    {
    	// TODO
      int blank_Row = -1;
	  int blank_Col = -1;
	  for(int row = 0; row < board.length; row++){
		  for(int col = 0; col < board[row].length; col++){
			  if(board[row][col] == 0){
				  blank_Row = row;
				  blank_Col = col;
			  }
		  }
	  }
	  if (blank_Row == -1 || blank_Col == -1){
		  throw new IllegalArgumentException();
	  }

		int [][] New_Board = new int[board.length][board[0].length];
		for (int r = 0; r < 3; r++) {
			for (int c = 0; c < 3; c++) {
				New_Board[r][c] = board[r][c];
			}
		}
		switch (m) {
			case LEFT:
				if (blank_Col == 2) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row, blank_Col + 1);
				break;

			case RIGHT:
				if (blank_Col == 0) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row, blank_Col - 1);
				break;

			case UP:
				if (blank_Row == 2) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row + 1, blank_Col);
				break;

			case DOWN:
				if (blank_Row == 0) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row - 1, blank_Col);
				break;

			case DBL_RIGHT:
				if (blank_Col != 2) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row, blank_Col - 1);
				swap(New_Board, blank_Row, blank_Col - 1, blank_Row, blank_Col - 2);
				break;

			case DBL_LEFT:
				if (blank_Col != 0) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row, blank_Col + 1);
				swap(New_Board, blank_Row, blank_Col + 1, blank_Row, blank_Col + 2);
				break;

			case DBL_DOWN:
				if (blank_Row != 2) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row - 1, blank_Col);
				swap(New_Board, blank_Row - 1, blank_Col, blank_Row - 2, blank_Col);
				break;

			case DBL_UP:
				if (blank_Row != 0) throw new IllegalArgumentException();
				swap(New_Board, blank_Row, blank_Col, blank_Row + 1, blank_Col);
				swap(New_Board, blank_Row + 1, blank_Col, blank_Row + 2, blank_Col);
				break;
		}

		State newState = new State(New_Board);
		newState.predecessor = this;
		newState.next = null;
		newState.previous = null;
		newState.move = m;
		newState.numMoves = numMoves + 1;

		if(newState.equals(this.predecessor)){
			return null;
		}
		return newState;
    }

	private void swap(int[][] board, int x, int y, int x1, int y1) {
		int temp = board[x][y];
		board[x][y] = board[x1][y1];
		board[x1][y1] = temp;
	}


	/**
     * Determines if the board configuration in this state can be rearranged into the goal configuration. 
     * According to the PowerPoint notes that introduce the 8-puzzle, we check if this state has an odd number 
     * of inversions.
     * 
     * @return true if the puzzle starting in this state can be rearranged into the goal state.
     */
    public boolean solvable()
    {
    	// TODO
		int [] FlatBoard = new int[9];
		int x = 0;
		for (int row = 0; row < 3; row++) {
			for (int col = 0; col < 3; col++) {
				FlatBoard[x] = board[row][col];
				x++;
			}
		}
		int inversions = 0;
		for (int i = 0; i < 9; i++) {
			for (int j = i + 1; j < 9; j++) {
				if (FlatBoard[i] != 0 && FlatBoard[j]!=0 && FlatBoard[i]>FlatBoard[j]){
					inversions++;
				}
			}
		}

		return inversions%2 ==1;
    }
    
    
    /**
     * Check if this state is the goal state, namely, if the array board[][] stores the following contents: 
     * 
     * 		1 2 3 
     * 		8 0 4 
     * 		7 6 5 
     * 
     * @return
     */
    public boolean isGoalState()
    {
		for (int row = 0; row < 3; row++) {
			for (int col = 0; col < 3; col++) {
				if (board[row][col] != GOAL[row][col]) {
					return false;
				}
			}
		}

		return true;
	}
    
    
    /**
     * Write the board configuration according to the following format:
     * 
     *     a) Output row by row in three lines with no indentations.  
     *     b) Two adjacent tiles in each row have exactly one blank in between. 
     *     c) The empty square is represented by a blank.  
     *     
     * For example, 
     * 
     * 2   3
     * 1 8 4
     * 7 6 5  
     * 
     */
    @Override
	public String toString()
	{
		StringBuilder s = new StringBuilder();

		for (int row = 0; row < 3; row++) {
			for (int col = 0; col < 3; col++) {
				int Num = board[row][col];

				if (Num == 0) {
					s.append("  ");
				} else {
					s.append(Num).append(" ");
				}
			}

			if (s.charAt(s.length() - 1) == ' ') {
				s.setLength(s.length() - 1);
			}
			s.append("\n");
		}
		return s.toString();
	}



	/**
     * Create a clone of this State object by copying over the board[][]. Set the links previous,
     * next, and predecessor to null. 
     * 
     * The method is called by SuccessorState(); 
     */
    @Override
    public Object clone()
    {
    	// TODO
		int[][] oldBoard = new int [board.length][board.length];
		for (int row = 0; row < board.length; row++) {
			for (int col = 0; col < board[row].length; col++) {
				oldBoard[row][col] = board[row][col];
			}
		}

		State copy = new State(oldBoard);
		copy.predecessor = null;
		copy.next = null;
		copy.previous = null;

    	return copy;
    }
  

    /**
     * Compare this state with the argument state.  Two states are equal if their arrays board[][] 
     * have the same content.
     */
    @Override 
    public boolean equals(Object o)
    {
    	// TODO
		if(o == null){
			return false;
		}

		if(!(o instanceof State)){
			return false;
		}

		State s = (State)o;

		for (int row = 0; row < board.length; row++) {
			for (int col = 0; col < board[row].length; col++) {
				if(this.board[row][col] != s.board[row][col]){
					return false;
				}
			}
		}
    	return true;
    }
        
    
    /**
     * Evaluate the cost of this state as the sum of the number of moves from the initial state and 
     * the estimated number of moves to the goal state using the heuristic stored in the instance 
     * variable heu. 
     * 
     * If heu == TileMismatch, add up numMoves and the return values from computeNumMismatchedTiles().
     * If heu == MahattanDist, add up numMoves and the return values of computeMahattanDistance(). 
     * If heu == DoubleMoveHeuristic, add up numMoves and the return value of computeNumSingleDoubleMoves(). 
     * 
     * @return estimated number of moves from the initial state to the goal state via this state.
     * @throws IllegalArgumentException if heuristic is none of TileMismatch, MahattanDist, DoubleMoveHeuristic. 
     */
    public int cost() throws IllegalArgumentException
    {
    	// TODO 
    	if(heu == Heuristic.TileMismatch){
			return numMoves + computeNumMismatchedTiles();
		}
		if(heu == Heuristic.ManhattanDist) {
			return computeManhattanDistance() + numMoves;
		}
		if (heu == Heuristic.DoubleMoveHeuristic){
			return computeNumSingleDoubleMoves() + numMoves;
		}
		else{
			throw new IllegalArgumentException("Please use a known heuristic");
		}
    }

    
    /**
     * Compare two states by the cost. Let c1 and c2 be the costs of this state and the argument state s.
     * 
     * @return -1 if c1 < c2 
     *          0 if c1 = c2 
     *          1 if c1 > c2 
     *          
     * Call the method cost(). This comparison will be used in maintaining the OPEN list by the A* algorithm.
     */
    @Override
    public int compareTo(State s)
    {
    	// TODO
		int c1 = this.cost();
		int c2 = s.cost();
		if(c1 < c2){
			return -1;
		}
		else if(c1 > c2){
			return 1;
		}
		else{
			return 0;
		}

    }
    

    /**
     * Return the value of the private variable numMismatchedTiles if it is non-negative, and compute its 
     * value otherwise. 
     * 
     * @return the number of mismatched tiles between this state and the goal state. 
     */
	private int computeNumMismatchedTiles()
	{
		// TODO
		if(numMismatchedTiles>0){
			return numMismatchedTiles;
		}
		for (int row = 0; row < board.length; row++) {
			for (int col = 0; col < board[row].length; col++) {
				if (board[row][col] != 0 && board[row][col] !=GOAL[row][col]) {
					numMismatchedTiles++;
				}
			}
		}
		return numMismatchedTiles;
	}

	
	/**
	 * Return the value of the private variable ManhattanDistance if it is non-negative, and compute its value 
	 * otherwise.
	 * 
	 * @return the Manhattan distance between this state and the goal state. 
	 */
	private int computeManhattanDistance()
	{
		// TODO
		int sum = 0;
		if(ManhattanDistance>0){
			return ManhattanDistance;
		}
		for (int row = 0; row < board.length; row++) {
			for (int col = 0; col < board[row].length; col++) {
                    int step = 0;

					if(step == 0){
						continue;
					}
					int Goal_Row = board[row][col];
					int Goal_Col = board[row][col];
					for(int i = 0; i < 3; i++){
						for (int j = 0; j < 3; j++){
							if(GOAL[i][j] == Goal_Row){
                                  Goal_Row = i;
								  Goal_Col = j;
							}

						}
					}
					sum += Math.abs(row - Goal_Row) + Math.abs(col - Goal_Col);
			}
		}

		return 0; 
	}
	
	
	/**
	 * Return the value of the private variable numSingleDoubleMoves if it is non-negative, and compute its value 
	 * otherwise. 
	 * 
	 * @return the value of the private variable numSingleDoubleMoves that bounds from below the number of moves, 
	 *         single or double, which will take this state to the goal state.
	 */
	private int computeNumSingleDoubleMoves()
	{
		// TODO
		if(numSingleDoubleMoves>0){
			return numSingleDoubleMoves;
		}
		int MisMatch = computeNumMismatchedTiles();
		int ManhattanDistance = computeManhattanDistance();

		int x = (MisMatch + 1)/2;
		int y = (ManhattanDistance + 1)/2;
		numSingleDoubleMoves = Math.max(x,y);
		return numSingleDoubleMoves;
	}
}


